apiVersion: v1
kind: Pod
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  containers:
  - name: proxy
    image: kenjasim/proxy
    ports:
    - containerPort: 6285
    env:
    - name: IP
      value: "11.0.0.152"
    - name: Port
      value: "30567"
